apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgroles-operator.fullname" . }}
  labels:
    {{- include "pgroles-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "pgroles-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.operator.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pgroles-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pgroles-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.operator.podSecurityContext | nindent 8 }}
      containers:
        - name: operator
          securityContext:
            {{- toYaml .Values.operator.securityContext | nindent 12 }}
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.operator.http.port }}
              protocol: TCP
          env:
            - name: OPERATOR_HTTP_ADDR
              value: "0.0.0.0:{{ .Values.operator.http.port }}"
            - name: CONTROLLER_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- with .Values.operator.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: {{ .Values.operator.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.operator.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.operator.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.operator.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: {{ .Values.operator.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.operator.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.operator.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.operator.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
