# Artifact Hub repository metadata file
# https://artifacthub.io/docs/topics/repositories/
repositoryID: 66868d5c-49d5-42bb-8525-8d26b195d8b6
owners:
  - name: Brian Thorne
    email: brian@hardbyte.nz
