---
apiVersion: pgroles.io/v1alpha1
kind: PostgresPolicy
metadata:
  name: invalid-policy
  namespace: default
spec:
  connection:
    secretRef:
      name: postgres-credentials
  interval: "5m"

  schemas:
    - name: reporting
      profiles: [missing-profile]
