import { Fragment, useEffect, useRef, useState } from 'react'
import Highlight, { defaultProps } from 'prism-react-renderer'

const setupStatements = [
  'CREATE ROLE pgroles_lab_alice LOGIN',
  'CREATE ROLE pgroles_lab_reporting',
  'CREATE ROLE pgroles_lab_owner',
  'GRANT CREATE ON DATABASE postgres TO pgroles_lab_owner',
  'SET ROLE pgroles_lab_owner',
  'CREATE SCHEMA pgroles_lab AUTHORIZATION pgroles_lab_owner',
  `CREATE TABLE pgroles_lab.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_name text NOT NULL,
  total_cents bigint NOT NULL
)`,
  `INSERT INTO pgroles_lab.orders (account_name, total_cents)
VALUES ('pgroles_lab_alice', 4200), ('someone_else', 9900)`,
  'RESET ROLE',
  'GRANT SELECT ON pgroles_lab.orders TO pgroles_lab_reporting',
  `GRANT pgroles_lab_reporting TO pgroles_lab_alice
  WITH INHERIT TRUE, SET TRUE`,
]

const experiments = [
  {
    id: 'missing-schema',
    chapter: 'Reach the table',
    title: 'A table grant is not enough',
    question:
      'Alice inherits SELECT on orders through reporting. Can she read the table without USAGE on its schema?',
    explanation:
      'No. PostgreSQL has to resolve pgroles_lab before it checks the table ACL. The SELECT grant exists, but the namespace gate fails first.',
    takeaway:
      'Access is a chain: a grant at a later gate cannot bypass an earlier one.',
    path: [
      ['Identity', 'Alice', 'pass'],
      ['Membership', 'INHERIT', 'pass'],
      ['Schema', 'USAGE absent', 'focus'],
      ['Table', 'SELECT granted', 'pass'],
      ['Rows', 'Awaiting query', 'muted'],
    ],
    expectedError: 'permission denied for schema pgroles_lab',
    highlightStatements: [0, 1],
    statements: [
      'SET ROLE pgroles_lab_alice',
      'SELECT * FROM pgroles_lab.orders ORDER BY id',
    ],
  },
  {
    id: 'complete-path',
    chapter: 'Reach the table',
    title: 'Repair the missing gate',
    question:
      'If reporting gains schema USAGE, will the unchanged table grant begin working?',
    explanation:
      'Yes. Schema USAGE makes the name reachable; the existing SELECT grant then authorizes the operation. PostgreSQL returns both rows.',
    takeaway:
      'Schema USAGE and table SELECT answer different questions, and a reader normally needs both.',
    path: [
      ['Identity', 'Alice', 'pass'],
      ['Membership', 'INHERIT', 'pass'],
      ['Schema', 'USAGE newly granted', 'focus'],
      ['Table', 'SELECT granted', 'pass'],
      ['Rows', 'Awaiting query', 'muted'],
    ],
    expectedResults: [
      {
        index: 0,
        rows: [
          { id: 1, account_name: 'pgroles_lab_alice', total_cents: 4200 },
          { id: 2, account_name: 'someone_else', total_cents: 9900 },
        ],
      },
    ],
    highlightStatements: [1],
    statements: [
      'RESET ROLE',
      'GRANT USAGE ON SCHEMA pgroles_lab TO pgroles_lab_reporting',
      'SET ROLE pgroles_lab_alice',
      'SELECT * FROM pgroles_lab.orders ORDER BY id',
    ],
  },
  {
    id: 'noinherit',
    chapter: 'Control inherited power',
    title: 'Membership can exist without active privileges',
    question:
      'If Alice remains a member but INHERIT is false, what do MEMBER, USAGE, and SET report—and can she still query?',
    explanation:
      'MEMBER is true, USAGE is false, and SET is true. Alice still belongs to reporting and may become it, but its privileges are dormant until she does.',
    takeaway:
      'Membership, automatic inheritance, and permission to SET ROLE are three separate facts.',
    path: [
      ['Identity', 'Alice', 'pass'],
      ['Membership', 'INHERIT off', 'focus'],
      ['Schema', 'USAGE via role', 'pass'],
      ['Table', 'SELECT via role', 'pass'],
      ['Rows', 'Awaiting query', 'muted'],
    ],
    expectedError: 'permission denied for schema pgroles_lab',
    expectedResults: [
      { index: 0, rows: [{ member: true, inherits: false, can_set: true }] },
    ],
    highlightStatements: [1, 2],
    statements: [
      'RESET ROLE',
      'REVOKE pgroles_lab_reporting FROM pgroles_lab_alice',
      `GRANT pgroles_lab_reporting TO pgroles_lab_alice
  WITH INHERIT FALSE, SET TRUE`,
      'SET ROLE pgroles_lab_alice',
      `SELECT
  pg_has_role(current_user, 'pgroles_lab_reporting', 'MEMBER') AS member,
  pg_has_role(current_user, 'pgroles_lab_reporting', 'USAGE')  AS inherits,
  pg_has_role(current_user, 'pgroles_lab_reporting', 'SET')    AS can_set`,
      'SELECT * FROM pgroles_lab.orders',
    ],
  },
  {
    id: 'set-role',
    chapter: 'Control inherited power',
    title: 'Switch to the capability deliberately',
    question:
      'What changes when the browser session runs SET ROLE reporting, and does the same query succeed?',
    explanation:
      'session_user remains the browser session’s bootstrap identity, while current_user becomes reporting. PostgreSQL now checks reporting’s privileges and the query succeeds.',
    takeaway:
      'SET ROLE changes the effective identity used for permission checks; it is not a second grant.',
    path: [
      ['Identity', 'reporting', 'focus'],
      ['Membership', 'SET allowed', 'pass'],
      ['Schema', 'USAGE granted', 'pass'],
      ['Table', 'SELECT granted', 'pass'],
      ['Rows', 'Awaiting query', 'muted'],
    ],
    expectedResults: [
      {
        index: 0,
        rows: [
          { session_user: 'postgres', current_user: 'pgroles_lab_reporting' },
        ],
      },
      { index: 1, rowCount: 2 },
    ],
    highlightStatements: [0],
    statements: [
      'SET ROLE pgroles_lab_reporting',
      'SELECT session_user, current_user',
      'SELECT * FROM pgroles_lab.orders ORDER BY id',
    ],
  },
  {
    id: 'future-object',
    chapter: 'Protect objects created tomorrow',
    title: 'A wildcard grant is a snapshot',
    question:
      'SELECT was granted on every table in the schema. Does that automatically cover a table created afterward?',
    explanation:
      'No. ALL TABLES expanded to the tables that existed when GRANT ran. The later refunds table has its own ACL and the query is denied.',
    takeaway:
      'Current objects and future objects are two different authorization problems.',
    path: [
      ['Identity', 'Alice', 'pass'],
      ['Membership', 'INHERIT', 'pass'],
      ['Schema', 'USAGE granted', 'pass'],
      ['New table', 'Created after grant', 'focus'],
      ['Rows', 'Awaiting query', 'muted'],
    ],
    expectedError: 'permission denied for table refunds',
    highlightStatements: [3, 5],
    statements: [
      'RESET ROLE',
      'REVOKE pgroles_lab_reporting FROM pgroles_lab_alice',
      'GRANT pgroles_lab_reporting TO pgroles_lab_alice WITH INHERIT TRUE',
      `GRANT SELECT ON ALL TABLES IN SCHEMA pgroles_lab
  TO pgroles_lab_reporting`,
      'SET ROLE pgroles_lab_owner',
      'CREATE TABLE pgroles_lab.refunds (id bigint PRIMARY KEY)',
      'RESET ROLE',
      'SET ROLE pgroles_lab_alice',
      'SELECT * FROM pgroles_lab.refunds',
    ],
  },
  {
    id: 'default-privilege',
    chapter: 'Protect objects created tomorrow',
    title: 'Defaults stamp the future ACL',
    question:
      'If app_owner defines a default, will a new table created as app_owner be readable immediately?',
    explanation:
      'Yes. The default belongs to the creator role, so the new payouts table receives reporting’s SELECT grant at creation time.',
    takeaway:
      'Use object grants for what exists and creator-specific default privileges for what comes next.',
    path: [
      ['Identity', 'Alice', 'pass'],
      ['Membership', 'INHERIT', 'pass'],
      ['Schema', 'USAGE granted', 'pass'],
      ['New table', 'Default applied', 'focus'],
      ['Rows', 'Awaiting query', 'muted'],
    ],
    expectedResults: [{ index: 0, rowCount: 0 }],
    highlightStatements: [1, 3],
    statements: [
      'RESET ROLE',
      `ALTER DEFAULT PRIVILEGES FOR ROLE pgroles_lab_owner
  IN SCHEMA pgroles_lab
  GRANT SELECT ON TABLES TO pgroles_lab_reporting`,
      'SET ROLE pgroles_lab_owner',
      'CREATE TABLE pgroles_lab.payouts (id bigint PRIMARY KEY)',
      'RESET ROLE',
      'SET ROLE pgroles_lab_alice',
      'SELECT * FROM pgroles_lab.payouts',
    ],
  },
  {
    id: 'row-security',
    chapter: 'Filter rows after access succeeds',
    title: 'Table access is not the final answer',
    question:
      'Alice may SELECT from orders. Can row security make the query succeed while returning only her row?',
    explanation:
      'Yes. The table ACL admits the query, then the policy evaluates each row against current_user. Only Alice’s row remains visible.',
    takeaway:
      'RLS is a second authorization layer after the object privilege check.',
    path: [
      ['Identity', 'Alice', 'pass'],
      ['Membership', 'INHERIT', 'pass'],
      ['Schema', 'USAGE granted', 'pass'],
      ['Table', 'SELECT granted', 'pass'],
      ['RLS', 'Policy enabled', 'focus'],
    ],
    expectedResults: [
      {
        index: 0,
        rows: [
          {
            rls_active: true,
            id: 1,
            account_name: 'pgroles_lab_alice',
            total_cents: 4200,
          },
        ],
      },
    ],
    highlightStatements: [2, 3],
    statements: [
      'RESET ROLE',
      'SET ROLE pgroles_lab_owner',
      'ALTER TABLE pgroles_lab.orders ENABLE ROW LEVEL SECURITY',
      `CREATE POLICY own_orders ON pgroles_lab.orders
  FOR SELECT
  USING (account_name = current_user)`,
      'RESET ROLE',
      'SET ROLE pgroles_lab_alice',
      `SELECT row_security_active('pgroles_lab.orders') AS rls_active,
       id, account_name, total_cents
FROM pgroles_lab.orders
ORDER BY id`,
    ],
  },
]

const chapters = [
  ...new Set(experiments.map((experiment) => experiment.chapter)),
]
const starterSql = `SELECT
  session_user,
  current_user,
  current_database();`

const pathStyles = {
  pass: 'border-emerald-400 bg-emerald-50/70 dark:border-emerald-700 dark:bg-emerald-950/20',
  focus:
    'border-amber-400 bg-amber-50 dark:border-amber-500 dark:bg-amber-950/25',
  blocked:
    'border-rose-400 bg-rose-50 dark:border-rose-700 dark:bg-rose-950/25',
  muted:
    'border-stone-200 bg-stone-50 text-stone-500 dark:border-stone-700 dark:bg-stone-800/40 dark:text-stone-400',
}

function AccessPath({ path }) {
  return (
    <div className="min-w-0 max-w-full overflow-hidden rounded-2xl border border-stone-200 bg-stone-50/60 p-3 dark:border-stone-700 dark:bg-stone-950/30">
      <p className="mb-3 mt-0 flex items-center justify-between gap-3 font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-stone-500 dark:text-stone-400">
        <span>Access path now</span>
        <span className="sm:hidden">Swipe →</span>
      </p>
      <ol className="m-0 grid max-w-full list-none auto-cols-[8.5rem] grid-flow-col gap-2 overflow-x-auto p-0 pb-1 sm:auto-cols-auto sm:grid-flow-row sm:grid-cols-5 sm:overflow-visible sm:pb-0">
        {path.map(([label, value, status]) => (
          <li
            key={label}
            className={`m-0 rounded-lg border-l-4 px-3 py-2 ${pathStyles[status]}`}
          >
            <span className="block font-mono text-[9px] font-semibold uppercase tracking-[0.12em] text-stone-500 dark:text-stone-400">
              {label}
            </span>
            <span className="mt-1 block text-xs font-semibold text-stone-900 dark:text-stone-100">
              {value}
            </span>
          </li>
        ))}
      </ol>
    </div>
  )
}

function SqlTokens({ code }) {
  return (
    <Highlight {...defaultProps} code={code} language="sql" theme={undefined}>
      {({ tokens, getTokenProps }) =>
        tokens.map((line, lineIndex) => (
          <Fragment key={lineIndex}>
            <span>
              {line
                .filter((token) => !token.empty)
                .map((token, tokenIndex) => (
                  <span key={tokenIndex} {...getTokenProps({ token })} />
                ))}
            </span>
            {lineIndex < tokens.length - 1 ? '\n' : null}
          </Fragment>
        ))
      }
    </Highlight>
  )
}

function SqlSource({
  statements,
  highlightStatements = [],
  label = 'SQL for this checkpoint',
  maxHeight = 'max-h-[24rem]',
}) {
  let nextLine = 1

  return (
    <pre
      aria-label={label}
      className={`language-sql m-0 ${maxHeight} overflow-auto rounded-none bg-[#0c0e12] py-4 text-xs leading-5`}
    >
      <code>
        {statements.map((statement, statementIndex) => {
          const code = `${statement};`
          const startLine = nextLine
          nextLine += code.split('\n').length
          const highlighted = highlightStatements.includes(statementIndex)

          return (
            <Highlight
              key={`${statementIndex}-${statement}`}
              {...defaultProps}
              code={code}
              language="sql"
              theme={undefined}
            >
              {({ tokens, getTokenProps }) => (
                <span
                  className={`block border-l-2 py-0.5 ${
                    highlighted
                      ? 'border-amber-400 bg-amber-300/10'
                      : 'border-transparent'
                  }`}
                >
                  {tokens.map((line, lineIndex) => (
                    <Fragment key={lineIndex}>
                      <span className="grid grid-cols-[2.75rem_1fr] px-3 sm:px-4">
                        <span
                          aria-hidden="true"
                          className={`select-none pr-3 text-right font-mono ${
                            highlighted ? 'text-amber-400' : 'text-stone-600'
                          }`}
                        >
                          {startLine + lineIndex}
                        </span>
                        <span className="min-w-0 whitespace-pre-wrap break-words">
                          {line
                            .filter((token) => !token.empty)
                            .map((token, tokenIndex) => (
                              <span
                                key={tokenIndex}
                                {...getTokenProps({ token })}
                              />
                            ))}
                        </span>
                      </span>
                      {lineIndex === tokens.length - 1 && (
                        <span className="block h-3" />
                      )}
                    </Fragment>
                  ))}
                </span>
              )}
            </Highlight>
          )
        })}
      </code>
    </pre>
  )
}

function SqlEditor({ value, onChange, disabled }) {
  const highlightRef = useRef(null)

  function syncScroll(event) {
    if (!highlightRef.current) return
    highlightRef.current.scrollTop = event.currentTarget.scrollTop
    highlightRef.current.scrollLeft = event.currentTarget.scrollLeft
  }

  return (
    <div className="relative min-h-[11rem] overflow-hidden rounded-xl border border-stone-700 bg-[#0c0e12] focus-within:border-amber-400 focus-within:ring-2 focus-within:ring-amber-400/20">
      <pre
        ref={highlightRef}
        aria-hidden="true"
        className="pointer-events-none absolute inset-0 m-0 min-h-[11rem] overflow-hidden whitespace-pre p-4 font-mono text-xs leading-6 text-stone-200"
      >
        <code>
          <SqlTokens code={value || ' '} />
        </code>
      </pre>
      <textarea
        aria-label="SQL playground"
        value={value}
        onChange={(event) => onChange(event.target.value)}
        onScroll={syncScroll}
        disabled={disabled}
        wrap="off"
        spellCheck="false"
        className="relative z-10 m-0 min-h-[11rem] w-full resize-y overflow-auto border-0 bg-transparent p-4 font-mono text-xs leading-6 text-transparent outline-none selection:bg-amber-300/30 disabled:cursor-wait"
        style={{ caretColor: '#f5f5f4', WebkitTextFillColor: 'transparent' }}
      />
    </div>
  )
}

function valueText(value) {
  if (value === null) return 'NULL'
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  return String(value)
}

function resultsMatchExpectations(results, expectations = []) {
  return expectations.every((expectation) => {
    const result = results[expectation.index]
    if (!result) return false
    if (
      expectation.rowCount !== undefined &&
      result.rows.length !== expectation.rowCount
    )
      return false
    if (!expectation.rows) return true
    if (result.rows.length !== expectation.rows.length) return false

    return expectation.rows.every((expectedRow, rowIndex) =>
      Object.entries(expectedRow).every(
        ([field, value]) => result.rows[rowIndex]?.[field] === value
      )
    )
  })
}

function ResultTable({ entry }) {
  return (
    <div className="overflow-x-auto rounded-xl border border-stone-700">
      <table className="min-w-full border-collapse font-mono text-xs">
        <thead className="bg-stone-800 text-left text-stone-300">
          <tr>
            {entry.fields.map((field) => (
              <th
                key={field}
                className="border-b border-stone-700 px-3 py-2 font-medium"
              >
                {field}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {entry.rows.length === 0 ? (
            <tr>
              <td
                colSpan={entry.fields.length}
                className="px-3 py-3 text-stone-500"
              >
                (0 rows)
              </td>
            </tr>
          ) : (
            entry.rows.map((row, rowIndex) => (
              <tr
                key={rowIndex}
                className="border-b border-stone-800 last:border-0"
              >
                {entry.fields.map((field) => (
                  <td key={field} className="px-3 py-2 text-stone-200">
                    {valueText(row[field])}
                  </td>
                ))}
              </tr>
            ))
          )}
        </tbody>
      </table>
    </div>
  )
}

function SqlOutput({ output, operation, kind = 'lesson' }) {
  const runningThisOutput =
    operation === kind || operation === 'booting' || operation === 'preparing'

  if (operation === 'booting') {
    return (
      <p className="m-0 text-sm text-stone-300">
        Downloading and starting PostgreSQL 18.3…
      </p>
    )
  }
  if (operation === 'preparing') {
    return (
      <p className="m-0 text-sm text-stone-300">
        Preparing Alice, reporting, and the orders table…
      </p>
    )
  }
  if (runningThisOutput) {
    return <p className="m-0 text-sm text-stone-300">Executing SQL…</p>
  }
  if (!output) {
    return (
      <p className="m-0 text-sm leading-6 text-stone-400">
        PostgreSQL’s command tags, rows, and exact error will appear here.
      </p>
    )
  }

  return (
    <div className="space-y-4">
      {output.commands.length > 0 && (
        <div
          className="flex flex-wrap gap-1.5"
          aria-label="PostgreSQL command results"
        >
          {output.commands.map((command, index) => (
            <span
              key={`${command}-${index}`}
              className="rounded-md border border-stone-700 bg-stone-800 px-2 py-1 font-mono text-[10px] text-stone-300"
            >
              {command}
            </span>
          ))}
        </div>
      )}
      {output.results.map((entry, index) => (
        <ResultTable key={index} entry={entry} />
      ))}
      {output.error && (
        <div
          className={`rounded-xl border px-4 py-3 font-mono text-xs ${
            kind === 'lesson' && output.passed
              ? 'border-amber-700/70 bg-amber-950/35 text-amber-200'
              : 'border-red-800 bg-red-950/40 text-red-200'
          }`}
        >
          <span className="mr-2 font-semibold">ERROR</span>
          {output.error}
        </div>
      )}
      {kind === 'lesson' ? (
        <p
          className={`m-0 text-sm font-semibold ${
            output.passed ? 'text-emerald-300' : 'text-red-300'
          }`}
        >
          {output.passed
            ? '✓ PostgreSQL matched the lesson’s expected behavior'
            : 'The result differs from the canonical lesson state. Reset the lesson to recover.'}
        </p>
      ) : !output.error ? (
        <p className="m-0 text-sm font-semibold text-emerald-300">
          ✓ SQL completed
        </p>
      ) : null}
    </div>
  )
}

function appendStatementResults(target, statementResults) {
  for (const result of statementResults) {
    if (result.command) target.commands.push(result.command)
    if (result.fields?.length > 0) {
      target.results.push({
        fields: result.fields.map((field) => field.name),
        rows: result.rows,
      })
    }
  }
}

async function executeStatements(database, statements) {
  const output = { commands: [], results: [], error: null }

  for (let index = 0; index < statements.length; index += 1) {
    try {
      const statementResults = await database.exec(`${statements[index]};`)
      appendStatementResults(output, statementResults)
    } catch (error) {
      output.error = error.message
      output.errorIndex = index
      break
    }
  }

  return output
}

export function PostgresPermissionLab() {
  const databaseRef = useRef(null)
  const databasePromiseRef = useRef(null)
  const lessonPreparedRef = useRef(false)
  const operationLockRef = useRef(false)
  const lessonStepRef = useRef(null)
  const [activeIndex, setActiveIndex] = useState(0)
  const [completed, setCompleted] = useState([])
  const [outputs, setOutputs] = useState({})
  const [operation, setOperation] = useState('idle')
  const [playgroundOpen, setPlaygroundOpen] = useState(false)
  const [playgroundSql, setPlaygroundSql] = useState(starterSql)
  const [playgroundOutput, setPlaygroundOutput] = useState(null)
  const experiment = experiments[activeIndex]
  const output = outputs[experiment.id]
  const running = operation !== 'idle'
  const chapterIndex = chapters.indexOf(experiment.chapter)
  const storyComplete = completed.length === experiments.length

  useEffect(
    () => () => {
      databaseRef.current?.close().catch(() => {})
    },
    []
  )

  async function ensureDatabase() {
    if (databaseRef.current) return databaseRef.current
    if (databasePromiseRef.current) return databasePromiseRef.current

    setOperation('booting')
    databasePromiseRef.current = import('@electric-sql/pglite')
      .then(({ PGlite }) => PGlite.create())
      .then((database) => {
        databaseRef.current = database
        return database
      })
      .finally(() => {
        databasePromiseRef.current = null
      })

    return databasePromiseRef.current
  }

  async function ensureLessonPrepared() {
    const database = await ensureDatabase()
    if (lessonPreparedRef.current) return database

    setOperation('preparing')
    const setupOutput = await executeStatements(database, setupStatements)
    if (setupOutput.error) {
      throw new Error(`Lesson setup failed: ${setupOutput.error}`)
    }
    lessonPreparedRef.current = true
    return database
  }

  async function runExperiment() {
    if (operationLockRef.current || running || output) return
    operationLockRef.current = true

    try {
      const database = await ensureLessonPrepared()
      setOperation('lesson')
      const result = await executeStatements(database, experiment.statements)
      const expectedErrorMatched = Boolean(
        experiment.expectedError &&
          result.errorIndex === experiment.statements.length - 1 &&
          result.error?.includes(experiment.expectedError)
      )
      const resultValuesMatch = resultsMatchExpectations(
        result.results,
        experiment.expectedResults
      )
      const passed =
        (experiment.expectedError
          ? expectedErrorMatched
          : result.error === null) && resultValuesMatch
      const lessonOutput = { ...result, passed }

      setOutputs((current) => ({ ...current, [experiment.id]: lessonOutput }))
      if (passed) {
        setCompleted((current) =>
          current.includes(experiment.id)
            ? current
            : [...current, experiment.id]
        )
      }
    } catch (error) {
      setOutputs((current) => ({
        ...current,
        [experiment.id]: {
          commands: [],
          results: [],
          error: error.message,
          passed: false,
        },
      }))
    } finally {
      setOperation('idle')
      operationLockRef.current = false
    }
  }

  async function runPlaygroundSql() {
    if (operationLockRef.current || running || playgroundSql.trim() === '')
      return
    operationLockRef.current = true
    setPlaygroundOutput(null)

    try {
      const database = await ensureLessonPrepared()
      setOperation('playground')
      const result = { commands: [], results: [], error: null }
      try {
        const statementResults = await database.exec(playgroundSql)
        appendStatementResults(result, statementResults)
      } catch (error) {
        result.error = error.message
      }
      setPlaygroundOutput(result)
    } catch (error) {
      setPlaygroundOutput({ commands: [], results: [], error: error.message })
    } finally {
      setOperation('idle')
      operationLockRef.current = false
    }
  }

  async function resetLab() {
    if (operationLockRef.current || running) return
    operationLockRef.current = true
    setOperation('resetting')
    const database = databaseRef.current
    databaseRef.current = null
    databasePromiseRef.current = null
    lessonPreparedRef.current = false

    try {
      if (database) await database.close()
    } catch {
      // The old instance is detached; the next action can still create a fresh database.
    } finally {
      setCompleted([])
      setOutputs({})
      setActiveIndex(0)
      setPlaygroundOpen(false)
      setPlaygroundOutput(null)
      setPlaygroundSql(starterSql)
      setOperation('idle')
      operationLockRef.current = false
    }
  }

  function showPrevious() {
    if (running || activeIndex === 0) return
    setPlaygroundOpen(false)
    setActiveIndex((index) => index - 1)
    requestAnimationFrame(() =>
      lessonStepRef.current?.scrollIntoView({
        behavior: 'smooth',
        block: 'start',
      })
    )
  }

  function showNext() {
    if (running || !output?.passed || activeIndex === experiments.length - 1)
      return
    setPlaygroundOpen(false)
    setActiveIndex((index) => index + 1)
    requestAnimationFrame(() =>
      lessonStepRef.current?.scrollIntoView({
        behavior: 'smooth',
        block: 'start',
      })
    )
  }

  return (
    <div className="not-prose my-10 overflow-hidden rounded-[2rem] border border-stone-300/90 bg-white shadow-[0_30px_80px_-52px_rgba(28,25,23,0.5)] dark:border-stone-700 dark:bg-stone-900 dark:shadow-none">
      <div className="border-b border-stone-300/80 bg-[linear-gradient(135deg,rgba(254,243,199,0.75),rgba(240,253,250,0.8))] px-5 py-6 dark:border-stone-700 dark:bg-[linear-gradient(135deg,rgba(120,53,15,0.2),rgba(19,78,74,0.2))] sm:px-7">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <p className="m-0 text-[11px] font-semibold uppercase tracking-[0.22em] text-amber-800 dark:text-amber-300">
            A guided PostgreSQL story
          </p>
          <a
            href="https://pglite.dev/"
            className="rounded-full border border-stone-300 bg-white/75 px-3 py-1 font-mono text-[10px] font-semibold text-stone-700 no-underline shadow-none dark:border-stone-700 dark:bg-stone-900/70 dark:text-stone-300"
          >
            PostgreSQL 18.3 · PGlite ↗
          </a>
        </div>
        <h2 className="mt-3 font-display text-2xl tracking-[-0.02em] text-stone-950 dark:text-white">
          Can Alice read the orders table?
        </h2>
        <p className="mb-0 mt-2 max-w-3xl text-sm leading-6 text-stone-700 dark:text-stone-300">
          Follow one query through schema access, membership, effective
          identity, future objects, and row security. Read the question, run the
          SQL, then explain the result.
        </p>
        <p className="mb-0 mt-3 max-w-3xl border-l-2 border-amber-400 pl-3 text-xs leading-5 text-stone-600 dark:text-stone-300">
          This browser database has one local session opened by{' '}
          <code>postgres</code>. The lesson uses <code>SET ROLE</code> to make
          Alice or reporting the effective <code>current_user</code>; in
          production Alice would normally be the authenticated{' '}
          <code>session_user</code>.
        </p>
      </div>

      <div className="border-b border-stone-200 px-5 py-5 dark:border-stone-800 sm:px-7">
        <div className="flex items-start justify-between gap-5">
          <div>
            <p className="m-0 font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-amber-700 dark:text-amber-300">
              Chapter {chapterIndex + 1} of {chapters.length} ·{' '}
              {experiment.chapter}
            </p>
            <p className="mb-0 mt-1 text-sm text-stone-600 dark:text-stone-300">
              Checkpoint {activeIndex + 1} of {experiments.length}
            </p>
          </div>
          <button
            type="button"
            onClick={resetLab}
            disabled={running}
            className="shrink-0 rounded-lg border border-stone-300 px-3 py-1.5 font-mono text-xs font-semibold text-stone-600 hover:border-amber-400 hover:text-stone-950 disabled:cursor-wait disabled:opacity-50 dark:border-stone-700 dark:text-stone-300 dark:hover:text-white"
          >
            Reset lesson
          </button>
        </div>
        <ol
          className="mt-4 flex gap-1.5"
          aria-label={`Checkpoint ${activeIndex + 1} of ${experiments.length}`}
        >
          {experiments.map((item, index) => (
            <li key={item.id} className="flex-1">
              <span
                className={`block h-1.5 rounded-full ${
                  completed.includes(item.id)
                    ? 'bg-emerald-500'
                    : index === activeIndex
                    ? 'bg-amber-400'
                    : 'bg-stone-200 dark:bg-stone-700'
                }`}
              >
                <span className="sr-only">
                  {item.title}
                  {completed.includes(item.id)
                    ? ': complete'
                    : index === activeIndex
                    ? ': current'
                    : ''}
                </span>
              </span>
            </li>
          ))}
        </ol>
      </div>

      <section
        ref={lessonStepRef}
        className="grid scroll-mt-24 gap-5 p-5 sm:p-7"
        aria-labelledby={`experiment-${experiment.id}`}
      >
        <div>
          <p className="m-0 font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-stone-500 dark:text-stone-400">
            Before you run it
          </p>
          <h3
            id={`experiment-${experiment.id}`}
            className="mt-2 font-display text-2xl tracking-[-0.02em] text-stone-950 dark:text-white"
          >
            {experiment.title}
          </h3>
          <p className="mb-0 mt-3 max-w-3xl text-base leading-7 text-stone-700 dark:text-stone-300">
            {experiment.question}
          </p>
        </div>

        <AccessPath path={experiment.path} />

        <div className="overflow-hidden rounded-2xl border border-stone-700 bg-[#0c0e12]">
          <div className="flex flex-col gap-4 border-b border-stone-700 bg-stone-900 px-4 py-3 sm:flex-row sm:items-center sm:justify-between">
            <p className="m-0 font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-stone-400">
              <span className="text-amber-300">Amber</span> marks the change
              under test
            </p>
            <button
              type="button"
              onClick={output && !output.passed ? resetLab : runExperiment}
              disabled={running || output?.passed}
              className="w-full rounded-xl border border-amber-300 bg-amber-300 px-5 py-2.5 font-mono text-xs font-bold text-stone-950 transition hover:bg-amber-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-amber-300 focus-visible:ring-offset-2 focus-visible:ring-offset-stone-900 disabled:cursor-wait disabled:border-stone-600 disabled:bg-stone-700 disabled:text-stone-400 sm:w-auto sm:shrink-0"
            >
              {operation === 'booting'
                ? 'Starting PostgreSQL…'
                : operation === 'preparing'
                ? 'Preparing lesson…'
                : operation === 'lesson'
                ? 'Running…'
                : output?.passed
                ? 'Observed'
                : output
                ? 'Reset lesson to retry'
                : 'Run checkpoint'}
            </button>
          </div>
          <SqlSource
            statements={experiment.statements}
            highlightStatements={experiment.highlightStatements}
          />
        </div>

        <div
          className="rounded-2xl border border-stone-700 bg-stone-950 p-5 text-stone-200"
          aria-live="polite"
          aria-busy={running}
        >
          <p className="mb-4 mt-0 font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-stone-500">
            What PostgreSQL said
          </p>
          <SqlOutput output={output} operation={operation} />
        </div>

        {output?.passed && (
          <div className="rounded-2xl border border-emerald-200 bg-emerald-50/70 p-5 dark:border-emerald-900 dark:bg-emerald-950/25">
            <p className="m-0 font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-emerald-700 dark:text-emerald-300">
              Why that happened
            </p>
            <p className="mb-0 mt-2 text-sm leading-6 text-stone-800 dark:text-stone-200">
              {experiment.explanation}
            </p>
            <p className="mb-0 mt-3 border-l-2 border-emerald-500 pl-3 text-sm font-semibold leading-6 text-stone-900 dark:text-white">
              {experiment.takeaway}
            </p>
          </div>
        )}

        <div className="flex flex-col-reverse gap-3 border-t border-stone-200 pt-5 dark:border-stone-800 sm:flex-row sm:items-center sm:justify-between">
          <button
            type="button"
            onClick={showPrevious}
            disabled={running || activeIndex === 0}
            className="rounded-lg border border-stone-300 px-4 py-2 text-sm font-semibold text-stone-600 hover:border-stone-500 hover:text-stone-950 disabled:cursor-not-allowed disabled:opacity-40 dark:border-stone-700 dark:text-stone-300 dark:hover:text-white"
          >
            ← Back
          </button>
          {activeIndex < experiments.length - 1 ? (
            <button
              type="button"
              onClick={showNext}
              disabled={running || !output?.passed}
              className="rounded-lg border border-stone-900 bg-stone-900 px-4 py-2 text-sm font-semibold text-white hover:bg-stone-700 disabled:cursor-not-allowed disabled:border-stone-200 disabled:bg-stone-100 disabled:text-stone-400 dark:border-white dark:bg-white dark:text-stone-900 dark:hover:bg-stone-200 dark:disabled:border-stone-700 dark:disabled:bg-stone-800 dark:disabled:text-stone-500"
            >
              Continue: {experiments[activeIndex + 1].title} →
            </button>
          ) : output?.passed ? (
            <p className="m-0 text-sm font-semibold text-emerald-700 dark:text-emerald-300">
              Story complete — the playground below now contains the finished
              database.
            </p>
          ) : (
            <p className="m-0 text-sm text-stone-500 dark:text-stone-400">
              Run the final checkpoint to complete the story.
            </p>
          )}
        </div>
      </section>

      <div className="border-t border-stone-200 bg-stone-50/70 dark:border-stone-800 dark:bg-stone-950/30">
        <button
          type="button"
          aria-expanded={storyComplete && playgroundOpen}
          aria-controls="postgres-sql-playground"
          onClick={() => setPlaygroundOpen((open) => !open)}
          disabled={!storyComplete || running}
          className="flex w-full items-center justify-between gap-4 px-5 py-5 text-left hover:bg-amber-50/60 disabled:cursor-not-allowed disabled:opacity-60 dark:hover:bg-stone-800/50 sm:px-7"
        >
          <span>
            <span className="block font-display text-lg text-stone-950 dark:text-white">
              Try your own SQL
            </span>
            <span className="mt-1 block text-sm leading-6 text-stone-600 dark:text-stone-400">
              {storyComplete
                ? 'Unlocked · explore the completed lesson database'
                : 'Complete the guided story to unlock free-form SQL'}
            </span>
          </span>
          <span aria-hidden="true" className="font-mono text-lg text-stone-500">
            {playgroundOpen ? '−' : '+'}
          </span>
        </button>

        {storyComplete && playgroundOpen && (
          <section
            id="postgres-sql-playground"
            className="grid gap-4 border-t border-stone-200 p-5 dark:border-stone-800 sm:p-7"
            aria-label="SQL playground"
          >
            <p className="m-0 text-sm leading-6 text-stone-600 dark:text-stone-300">
              Run any PostgreSQL SQL against the completed lesson state. Changes
              persist in this browser database; <strong>Reset lesson</strong>{' '}
              restores the canonical story.
            </p>
            <SqlEditor
              value={playgroundSql}
              onChange={setPlaygroundSql}
              disabled={running}
            />
            <div className="flex justify-end">
              <button
                type="button"
                onClick={runPlaygroundSql}
                disabled={running || playgroundSql.trim() === ''}
                className="w-full rounded-xl border border-amber-300 bg-amber-300 px-5 py-2.5 font-mono text-xs font-bold text-stone-950 hover:bg-amber-200 disabled:cursor-wait disabled:border-stone-300 disabled:bg-stone-200 disabled:text-stone-500 sm:w-auto"
              >
                {operation === 'playground'
                  ? 'Running SQL…'
                  : running
                  ? 'PostgreSQL is busy…'
                  : 'Run SQL'}
              </button>
            </div>
            <div
              className="rounded-2xl border border-stone-700 bg-stone-950 p-5 text-stone-200"
              aria-live="polite"
              aria-busy={operation === 'playground'}
            >
              <p className="mb-4 mt-0 font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-stone-500">
                Playground output
              </p>
              <SqlOutput
                output={playgroundOutput}
                operation={operation}
                kind="playground"
              />
            </div>
          </section>
        )}
      </div>

      <details className="border-t border-stone-200 px-5 py-4 dark:border-stone-800 sm:px-7">
        <summary className="cursor-pointer text-sm font-semibold text-stone-600 hover:text-stone-950 dark:text-stone-300 dark:hover:text-white">
          Show the lesson setup SQL
        </summary>
        <p className="mb-4 mt-3 text-sm leading-6 text-stone-500 dark:text-stone-400">
          The lesson prepares three roles, a schema, the orders table, two rows,
          and Alice’s initial inherited table grant. It runs once before the
          first query.
        </p>
        <div className="overflow-hidden rounded-2xl border border-stone-700">
          <SqlSource
            statements={setupStatements}
            label="Lesson setup SQL"
            maxHeight="max-h-[24rem]"
          />
        </div>
      </details>
    </div>
  )
}
