import {Fragment, useEffect, useRef, useState} from 'react'
import Highlight, {defaultProps} from 'prism-react-renderer'

const experiments = [
  {
    id: 'bootstrap',
    shortTitle: 'Missing schema access',
    title: 'Give Alice a table grant but no schema access',
    section: 'Access is a chain of gates',
    sectionHref: '#access-is-a-chain-of-gates',
    expected: 'PostgreSQL returns permission denied for schema pgroles_lab.',
    expectedError: 'permission denied for schema pgroles_lab',
    highlightStatements: [9, 10, 11, 12],
    statements: [
      'CREATE ROLE pgroles_lab_alice LOGIN',
      'CREATE ROLE pgroles_lab_reporting',
      'CREATE ROLE pgroles_lab_owner',
      'GRANT CREATE ON DATABASE postgres TO pgroles_lab_owner',
      'SET ROLE pgroles_lab_owner',
      'CREATE SCHEMA pgroles_lab AUTHORIZATION pgroles_lab_owner',
      `CREATE TABLE pgroles_lab.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_name text NOT NULL,
  total_cents bigint NOT NULL
)`,
      `INSERT INTO pgroles_lab.orders (account_name, total_cents)
VALUES ('pgroles_lab_alice', 4200), ('someone_else', 9900)`,
      'RESET ROLE',
      'GRANT SELECT ON pgroles_lab.orders TO pgroles_lab_reporting',
      `GRANT pgroles_lab_reporting TO pgroles_lab_alice
  WITH INHERIT TRUE, SET TRUE`,
      'SET ROLE pgroles_lab_alice',
      'SELECT * FROM pgroles_lab.orders',
    ],
  },
  {
    id: 'complete-path',
    shortTitle: 'Complete path',
    title: 'Add the missing namespace grant',
    section: 'Database, schema, and object privileges',
    sectionHref: '#database-schema-and-object-privileges-do-different-jobs',
    expected: 'The same SELECT now returns both rows.',
    expectedResults: [
      {index: 0, rows: [
        {id: 1, account_name: 'pgroles_lab_alice', total_cents: 4200},
        {id: 2, account_name: 'someone_else', total_cents: 9900},
      ]},
    ],
    highlightStatements: [1, 2, 3],
    statements: [
      'RESET ROLE',
      'GRANT USAGE ON SCHEMA pgroles_lab TO pgroles_lab_reporting',
      'SET ROLE pgroles_lab_alice',
      'SELECT * FROM pgroles_lab.orders ORDER BY id',
    ],
  },
  {
    id: 'noinherit',
    shortTitle: 'NOINHERIT membership',
    title: 'Keep membership but stop automatic privilege inheritance',
    section: 'Membership is a directed edge',
    sectionHref: '#membership-is-a-directed-edge',
    expected: 'MEMBER is true, USAGE is false, SET is true, and the table query is denied.',
    expectedError: 'permission denied for schema pgroles_lab',
    expectedResults: [
      {index: 0, rows: [{member: true, inherits: false, can_set: true}]},
    ],
    highlightStatements: [1, 2, 3, 4, 5],
    statements: [
      'RESET ROLE',
      'REVOKE pgroles_lab_reporting FROM pgroles_lab_alice',
      `GRANT pgroles_lab_reporting TO pgroles_lab_alice
  WITH INHERIT FALSE, SET TRUE`,
      'SET ROLE pgroles_lab_alice',
      `SELECT
  pg_has_role(current_user, 'pgroles_lab_reporting', 'MEMBER') AS member,
  pg_has_role(current_user, 'pgroles_lab_reporting', 'USAGE')  AS inherits,
  pg_has_role(current_user, 'pgroles_lab_reporting', 'SET')    AS can_set`,
      'SELECT * FROM pgroles_lab.orders',
    ],
  },
  {
    id: 'set-role',
    shortTitle: 'SET ROLE',
    title: 'Deliberately switch to the capability role',
    section: 'The two names in every session',
    sectionHref: '#the-two-names-in-every-session',
    expected: 'session_user stays postgres, current_user becomes pgroles_lab_reporting, and SELECT succeeds.',
    expectedResults: [
      {index: 0, rows: [{session_user: 'postgres', current_user: 'pgroles_lab_reporting'}]},
      {index: 1, rowCount: 2},
    ],
    highlightStatements: [0, 1, 2],
    statements: [
      'SET ROLE pgroles_lab_reporting',
      'SELECT session_user, current_user',
      'SELECT * FROM pgroles_lab.orders ORDER BY id',
    ],
  },
  {
    id: 'future-object',
    shortTitle: 'A new table',
    title: 'Create a table after the wildcard grant',
    section: 'Existing objects and future objects',
    sectionHref: '#existing-objects-and-future-objects-are-separate-problems',
    expected: 'The new table is denied: ALL TABLES changed only objects that existed when GRANT ran.',
    expectedError: 'permission denied for table refunds',
    highlightStatements: [3, 4, 5, 7, 8],
    statements: [
      'RESET ROLE',
      'REVOKE pgroles_lab_reporting FROM pgroles_lab_alice',
      'GRANT pgroles_lab_reporting TO pgroles_lab_alice WITH INHERIT TRUE',
      `GRANT SELECT ON ALL TABLES IN SCHEMA pgroles_lab
  TO pgroles_lab_reporting`,
      'SET ROLE pgroles_lab_owner',
      'CREATE TABLE pgroles_lab.refunds (id bigint PRIMARY KEY)',
      'RESET ROLE',
      'SET ROLE pgroles_lab_alice',
      'SELECT * FROM pgroles_lab.refunds',
    ],
  },
  {
    id: 'default-privilege',
    shortTitle: 'Creator defaults',
    title: 'Stamp the right ACL onto a future table',
    section: 'Existing objects and future objects',
    sectionHref: '#existing-objects-and-future-objects-are-separate-problems',
    expected: 'The new payouts table is readable immediately, before any pgroles reconcile.',
    expectedResults: [{index: 0, rowCount: 0}],
    highlightStatements: [1, 2, 3, 5, 6],
    statements: [
      'RESET ROLE',
      `ALTER DEFAULT PRIVILEGES FOR ROLE pgroles_lab_owner
  IN SCHEMA pgroles_lab
  GRANT SELECT ON TABLES TO pgroles_lab_reporting`,
      'SET ROLE pgroles_lab_owner',
      'CREATE TABLE pgroles_lab.payouts (id bigint PRIMARY KEY)',
      'RESET ROLE',
      'SET ROLE pgroles_lab_alice',
      'SELECT * FROM pgroles_lab.payouts',
    ],
  },
  {
    id: 'row-security',
    shortTitle: 'Row security',
    title: 'Allow the query but filter the rows',
    section: 'Row security is a second authorization system',
    sectionHref: '#row-security-is-a-second-authorization-system',
    expected: 'The SELECT succeeds but returns only Alice’s row.',
    expectedResults: [
      {index: 0, rows: [{rls_active: true, id: 1, account_name: 'pgroles_lab_alice', total_cents: 4200}]},
    ],
    highlightStatements: [2, 3, 5, 6],
    statements: [
      'RESET ROLE',
      'SET ROLE pgroles_lab_owner',
      'ALTER TABLE pgroles_lab.orders ENABLE ROW LEVEL SECURITY',
      `CREATE POLICY own_orders ON pgroles_lab.orders
  FOR SELECT
  USING (account_name = current_user)`,
      'RESET ROLE',
      'SET ROLE pgroles_lab_alice',
      `SELECT row_security_active('pgroles_lab.orders') AS rls_active,
       id, account_name, total_cents
FROM pgroles_lab.orders
ORDER BY id`,
    ],
  },
]

function SqlSource({experiment}) {
  let nextLine = 1

  return (
    <pre className="language-sql m-0 max-h-[32rem] overflow-auto rounded-none bg-[#0c0e12] py-4 text-xs leading-5">
      <code>
        {experiment.statements.map((statement, statementIndex) => {
          const code = `${statement};`
          const startLine = nextLine
          nextLine += code.split('\n').length
          const highlighted = experiment.highlightStatements.includes(statementIndex)

          return (
            <Highlight key={`${experiment.id}-${statementIndex}`} {...defaultProps} code={code} language="sql" theme={undefined}>
              {({tokens, getTokenProps}) => (
                <span className={`block border-l-2 py-0.5 ${highlighted ? 'border-amber-400 bg-amber-300/10' : 'border-transparent'}`}>
                  {tokens.map((line, lineIndex) => (
                    <Fragment key={lineIndex}>
                      <span className="grid grid-cols-[2.75rem_1fr] px-3 sm:px-4">
                        <span aria-hidden="true" className={`select-none pr-3 text-right font-mono ${highlighted ? 'text-amber-400' : 'text-stone-600'}`}>
                          {startLine + lineIndex}
                        </span>
                        <span className="min-w-0 whitespace-pre-wrap break-words">
                          {line.filter((token) => !token.empty).map((token, tokenIndex) => (
                            <span key={tokenIndex} {...getTokenProps({token})} />
                          ))}
                        </span>
                      </span>
                      {lineIndex === tokens.length - 1 && <span className="block h-3" />}
                    </Fragment>
                  ))}
                </span>
              )}
            </Highlight>
          )
        })}
      </code>
    </pre>
  )
}

function valueText(value) {
  if (value === null) return 'NULL'
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  return String(value)
}

function resultsMatchExpectations(results, expectations = []) {
  return expectations.every((expectation) => {
    const result = results[expectation.index]
    if (!result) return false
    if (expectation.rowCount !== undefined && result.rows.length !== expectation.rowCount) return false
    if (!expectation.rows) return true
    if (result.rows.length !== expectation.rows.length) return false

    return expectation.rows.every((expectedRow, rowIndex) =>
      Object.entries(expectedRow).every(([field, value]) => result.rows[rowIndex]?.[field] === value)
    )
  })
}

function ResultTable({entry}) {
  return (
    <div className="overflow-x-auto rounded-xl border border-stone-700">
      <table className="min-w-full border-collapse font-mono text-xs">
        <thead className="bg-stone-800 text-left text-stone-300">
          <tr>
            {entry.fields.map((field) => <th key={field} className="border-b border-stone-700 px-3 py-2 font-medium">{field}</th>)}
          </tr>
        </thead>
        <tbody>
          {entry.rows.length === 0 ? (
            <tr><td colSpan={entry.fields.length} className="px-3 py-3 text-stone-500">(0 rows)</td></tr>
          ) : entry.rows.map((row, rowIndex) => (
            <tr key={rowIndex} className="border-b border-stone-800 last:border-0">
              {entry.fields.map((field) => <td key={field} className="px-3 py-2 text-stone-200">{valueText(row[field])}</td>)}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

function Output({output, status}) {
  if (status === 'booting') {
    return <p className="m-0 text-sm text-stone-300">Downloading and starting PostgreSQL 18.3…</p>
  }
  if (status === 'running') {
    return <p className="m-0 text-sm text-stone-300">Executing each statement in order…</p>
  }
  if (!output) {
    return <p className="m-0 text-sm leading-6 text-stone-400">Run the highlighted SQL to see PostgreSQL’s command tags, rows, and exact error here.</p>
  }

  return (
    <div className="space-y-4">
      {output.commands.length > 0 && (
        <div className="flex flex-wrap gap-1.5" aria-label="PostgreSQL command results">
          {output.commands.map((command, index) => (
            <span key={`${command}-${index}`} className="rounded-md border border-stone-700 bg-stone-800 px-2 py-1 font-mono text-[10px] text-stone-300">{command}</span>
          ))}
        </div>
      )}
      {output.results.map((entry, index) => <ResultTable key={index} entry={entry} />)}
      {output.error && (
        <div className={`rounded-xl border px-4 py-3 font-mono text-xs ${output.passed ? 'border-amber-700/70 bg-amber-950/35 text-amber-200' : 'border-red-800 bg-red-950/40 text-red-200'}`}>
          <span className="mr-2 font-semibold">ERROR</span>{output.error}
        </div>
      )}
      <p className={`m-0 text-sm font-semibold ${output.passed ? 'text-emerald-300' : 'text-red-300'}`}>
        {output.passed ? '✓ Observed the expected PostgreSQL behavior' : 'The result did not match this experiment’s expected behavior'}
      </p>
    </div>
  )
}

export function PostgresPermissionLab() {
  const databaseRef = useRef(null)
  const [activeIndex, setActiveIndex] = useState(0)
  const [completed, setCompleted] = useState([])
  const [outputs, setOutputs] = useState({})
  const [status, setStatus] = useState('idle')
  const experiment = experiments[activeIndex]
  const unlocked = activeIndex === 0 || completed.includes(experiments[activeIndex - 1].id)

  useEffect(() => () => {
    databaseRef.current?.close().catch(() => {})
  }, [])

  async function ensureDatabase() {
    if (databaseRef.current) return databaseRef.current
    setStatus('booting')
    const {PGlite} = await import('@electric-sql/pglite')
    databaseRef.current = await PGlite.create()
    return databaseRef.current
  }

  async function runExperiment() {
    if (!unlocked || status === 'booting' || status === 'running') return

    try {
      const database = await ensureDatabase()
      setStatus('running')
      const commands = []
      const results = []
      let error = null
      let expectedErrorMatched = false

      for (let index = 0; index < experiment.statements.length; index += 1) {
        try {
          const statementResults = await database.exec(`${experiment.statements[index]};`)
          for (const result of statementResults) {
            if (result.command) commands.push(result.command)
            if (result.fields?.length > 0) {
              results.push({
                fields: result.fields.map((field) => field.name),
                rows: result.rows,
              })
            }
          }
        } catch (statementError) {
          error = statementError.message
          expectedErrorMatched = Boolean(
            experiment.expectedError &&
            index === experiment.statements.length - 1 &&
            error.includes(experiment.expectedError)
          )
          break
        }
      }

      const resultValuesMatch = resultsMatchExpectations(results, experiment.expectedResults)
      const passed = (experiment.expectedError ? expectedErrorMatched : error === null) && resultValuesMatch
      setOutputs((current) => ({...current, [experiment.id]: {commands, results, error, passed}}))
      if (passed) {
        setCompleted((current) => current.includes(experiment.id) ? current : [...current, experiment.id])
      }
      setStatus('idle')
    } catch (error) {
      setOutputs((current) => ({...current, [experiment.id]: {commands: [], results: [], error: error.message, passed: false}}))
      setStatus('idle')
    }
  }

  async function resetLab() {
    if (status === 'booting' || status === 'running') return
    setStatus('booting')
    const database = databaseRef.current
    databaseRef.current = null
    try {
      if (database) await database.close()
    } catch {
      // The old instance is already detached; keep Reset usable and let the next Run create a fresh database.
    } finally {
      setCompleted([])
      setOutputs({})
      setActiveIndex(0)
      setStatus('idle')
    }
  }

  const running = status === 'booting' || status === 'running'
  const output = outputs[experiment.id]

  return (
    <div className="not-prose my-10 overflow-hidden rounded-[2rem] border border-stone-300/90 bg-white shadow-[0_30px_80px_-52px_rgba(28,25,23,0.5)] dark:border-stone-700 dark:bg-stone-900 dark:shadow-none">
      <div className="border-b border-stone-300/80 bg-[linear-gradient(135deg,rgba(254,243,199,0.75),rgba(240,253,250,0.8))] px-5 py-6 sm:px-7 dark:border-stone-700 dark:bg-[linear-gradient(135deg,rgba(120,53,15,0.2),rgba(19,78,74,0.2))]">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <p className="m-0 text-[11px] font-semibold uppercase tracking-[0.22em] text-amber-800 dark:text-amber-300">Real PostgreSQL permission lab</p>
          <a href="https://pglite.dev/" className="rounded-full border border-stone-300 bg-white/75 px-3 py-1 font-mono text-[10px] font-semibold text-stone-700 no-underline shadow-none dark:border-stone-700 dark:bg-stone-900/70 dark:text-stone-300">PostgreSQL 18.3 · PGlite ↗</a>
        </div>
        <p className="mt-3 font-display text-2xl tracking-[-0.02em] text-stone-950 dark:text-white">Break access, observe it, then repair it</p>
        <p className="mt-2 max-w-3xl text-sm leading-6 text-stone-700 dark:text-stone-300">Each Run click executes the highlighted SQL against an isolated PostgreSQL 18.3 database in this browser. Nothing connects to your systems.</p>
      </div>

      <div className="border-b border-stone-200 px-4 py-4 dark:border-stone-800 sm:px-6">
        <div className="flex items-center justify-between gap-4">
          <p className="m-0 text-sm leading-6 text-stone-700 dark:text-stone-300">Run 1–7 in order. Each result unlocks the next experiment.</p>
          <button type="button" onClick={resetLab} disabled={running} className="shrink-0 rounded-lg border border-stone-300 px-3 py-1.5 font-mono text-xs font-semibold text-stone-600 hover:border-amber-400 hover:text-stone-950 disabled:cursor-wait disabled:opacity-50 dark:border-stone-700 dark:text-stone-300 dark:hover:text-white">Reset lab</button>
        </div>
        <ol className="mt-3 flex gap-2 overflow-x-auto pb-1" aria-label="Permission lab experiments">
          {experiments.map((item, index) => {
            const isComplete = completed.includes(item.id)
            const isUnlocked = index === 0 || completed.includes(experiments[index - 1].id)
            return (
              <li key={item.id}>
                <button
                  type="button"
                  aria-current={index === activeIndex ? 'step' : undefined}
                  disabled={!isUnlocked || running}
                  onClick={() => setActiveIndex(index)}
                  className={`shrink-0 rounded-full border px-3 py-2 text-left text-xs font-semibold transition focus:outline-none focus-visible:ring-2 focus-visible:ring-amber-500 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-40 dark:focus-visible:ring-offset-stone-900 ${index === activeIndex ? 'border-stone-900 bg-stone-900 text-white dark:border-white dark:bg-white dark:text-stone-900' : 'border-stone-300 bg-white text-stone-700 hover:border-amber-400 hover:text-stone-950 dark:border-stone-700 dark:bg-stone-900 dark:text-stone-300 dark:hover:border-amber-500 dark:hover:text-white'}`}
                >
                  <span className="mr-2 font-mono text-[10px] opacity-60">{isComplete ? '✓' : String(index + 1).padStart(2, '0')}</span>{item.shortTitle}
                </button>
              </li>
            )
          })}
        </ol>
      </div>

      <section className="grid gap-5 p-5 sm:p-7" aria-labelledby={`experiment-${experiment.id}`}>
        <div className="overflow-hidden rounded-2xl border border-stone-700 bg-[#0c0e12]">
          <div className="border-b border-stone-700 bg-stone-900 px-5 py-4">
            <div className="flex flex-col items-stretch gap-4 sm:flex-row sm:items-start sm:justify-between">
              <div className="min-w-0 flex-1">
                <a href={experiment.sectionHref} className="font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-amber-300 no-underline shadow-none">Concept · {experiment.section} ↘</a>
                <h3 id={`experiment-${experiment.id}`} className="mt-1 font-display text-xl text-white">{experiment.title}</h3>
                <p className="mt-2 text-sm leading-6 text-stone-300"><span className="font-semibold text-white">Observe:</span> {experiment.expected}</p>
              </div>
              <button
                type="button"
                onClick={runExperiment}
                disabled={!unlocked || running || Boolean(output)}
                className="w-full rounded-xl border border-amber-300 bg-amber-300 px-5 py-2.5 font-mono text-xs font-bold text-stone-950 transition hover:bg-amber-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-amber-300 focus-visible:ring-offset-2 focus-visible:ring-offset-stone-900 disabled:cursor-wait disabled:border-stone-600 disabled:bg-stone-700 disabled:text-stone-400 sm:w-auto sm:shrink-0"
              >
                {status === 'booting' ? 'Starting PostgreSQL…' : status === 'running' ? 'Running…' : output?.passed ? 'Completed' : output ? 'Reset to retry' : 'Run experiment'}
              </button>
            </div>
          </div>
          <SqlSource experiment={experiment} />
        </div>

        <div className="rounded-2xl border border-stone-700 bg-stone-950 p-5 text-stone-200" aria-live="polite" aria-busy={running}>
          <p className="mb-4 mt-0 font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-stone-500">Observed PostgreSQL output</p>
          <Output output={output} status={status} />
        </div>

        <p className="m-0 text-xs leading-5 text-stone-500 dark:text-stone-400">The first run downloads the WebAssembly engine. PGlite is Apache-2.0 licensed and compiles upstream PostgreSQL for the browser. This lab is ephemeral: Reset lab closes the database and starts the lesson again from step 1.</p>
      </section>
    </div>
  )
}
